<!doctype html>
<html lang="en">
  <head>
    <title>Get Started!</title>
  </head>
  <body>
    <p>Static text</p>

    <?php echo "<p>This text was generated by PHP!</p>" ; ?>

    <p><?php echo "And so was this"; ?> </p>

    <p>Put your first and last name inside the quotes below.</p>

    <p><?php echo "Michael Moore"; ?></p>

    <p>This text was not.</p>
  </body>
</html>
